### ISSUE TITLE
problem with DB at first run (I can't get it to work)

### ISSUE THREAD

**Issue by connect192168** [push-things/django-th#288]
* Version of the project you use
django-th branch:master
git cloned at 11:12 UTC+1 24th April 2018
python version 3.5.2
I used git clone https://github.com/foxmask/django-th/ for the install
OS: ubuntu xenial 16.04 on AWS
AWS instance is dedicated to django_th  (nothing else running off the instance)

* Details of the error/behavior:
I was following the read-the-docs install instructions and got to the running section.

It just threw an error when I ran python manage.py migrate .
error:

`(myproject) ubuntu@ip-172-31-9-72:~/myproject/django-th$ python3 manage.py migrate
Traceback (most recent call last):
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 162, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 79, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/myproject/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 162, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file`

any help fixing this would be greatly appreciated.

**Comment by connect192168** [comment]
I just tried running the command using sudo and I get this:
```
(myproject) ubuntu@ip-172-31-9-72:~/myproject/django-th$ sudo python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
```

**Comment by foxmask** [comment]
I just made a try 
```python
foxmask@localhost:~/DjangoVirtualEnv $ python3.6 -m venv test
foxmask@localhost:~/DjangoVirtualEnv $ cd test
foxmask@localhost:~/DjangoVirtualEnv/test $ ls
bin  include  lib  lib64  pyvenv.cfg
foxmask@localhost:~/DjangoVirtualEnv/test $ git clone https://github.com/foxmask/django-th/ 
Clonage dans 'django-th'...
remote: Counting objects: 7359, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 7359 (delta 30), reused 40 (delta 17), pack-reused 7280
Réception d'objets: 100% (7359/7359), 4.24 MiB | 160.00 KiB/s, fait.
Résolution des deltas: 100% (4990/4990), fait.
foxmask@localhost:~/DjangoVirtualEnv/test $ ls
bin  django-th  include  lib  lib64  pyvenv.cfg
foxmask@localhost:~/DjangoVirtualEnv/test $ cd django-th/
? ~/DjangoVirtualEnv/test/django-th [master|?] 
13:12 $ source ../bin/activate
(test) ? ~/DjangoVirtualEnv/test/django-th [master|?] 
13:12 $ pip install -r requirements.txt 
Collecting arrow (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e0/86/4eb5228a43042e9a80fe8c84093a8a36f5db34a3767ebd5e1e7729864e7b/arrow-0.12.1.tar.gz (65kB)
    100% |????????????????????????????????| 71kB 2.1MB/s 
Collecting awesome-slugify (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/34/39/79ef4e640c3651b40de7812f5fcd04698abf14de4f57a81e12b6c753d168/awesome-slugify-1.6.5.tar.gz
Collecting djangorestframework<4.0,>=3.7.7 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/90/30/ad1148098ff0c375df2a30cc4494ed953cf7551fc1ecec30fc951c712d20/djangorestframework-3.8.2-py2.py3-none-any.whl (923kB)
    100% |????????????????????????????????| 931kB 1.4MB/s 
Collecting Django<3.0,>=2.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/89/f9/94c20658f0cdecc2b6607811e2c0bb042408a51f589e5ad0cb0eac3236a1/Django-2.0.4-py3-none-any.whl
Collecting django-environ (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/0e/04/8a2b9d21ed73761b8e12201aa0531c0b0971fe8a832c9311cb3c2529fa98/django_environ-0.4.4-py2.py3-none-any.whl
Collecting django-filter (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ee/99/eb6f20b0ca4e2800279963599971e70c71767b9d151f44fcbcd1caa19f32/django_filter-1.1.0-py2.py3-none-any.whl (45kB)
    100% |????????????????????????????????| 51kB 6.8MB/s 
Collecting django-formtools (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/97/3f/b8e04c41c028d5cdad651393abea1f686d846c717d8ab5d5ebe2974f711c/django_formtools-2.1-py2.py3-none-any.whl (132kB)
    100% |????????????????????????????????| 133kB 5.4MB/s 
Collecting django-js-reverse (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/e8/00/ce789cf5fb65fa7f8e8babf647e5afbef5a712cc4e66d890ac41c10a0f1d/django_js_reverse-0.8.1-py2.py3-none-any.whl
Collecting django-redis (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/d5/3c/184b7a962f2aa5e49388ced9664a308b8d1b9864dc6afe7adb2a8302b5c4/django_redis-4.9.0-py2.py3-none-any.whl
Collecting evernote3==1.25.12 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/7c/7f/6494d7f688c1ce5cda11467db0cac426de983cd3b353683cff0f9257301a/evernote3-1.25.12.tar.gz (126kB)
    100% |????????????????????????????????| 133kB 5.8MB/s 
Collecting feedparser (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2 (192kB)
    100% |????????????????????????????????| 194kB 3.9MB/s 
Collecting github3.py (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/42/3b/900fc188e92dc70362123a188471050acb5c49a0dc3e206931e764d856d7/github3.py-1.1.0-py2.py3-none-any.whl (141kB)
    100% |????????????????????????????????| 143kB 4.8MB/s 
Collecting Mastodon.py (from -r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/3d/d8/3207e3eb9cc0e784975fdc1f44048cd490e4f3a8baf41f1630a129c823ea/Mastodon.py-1.2.2-py2.py3-none-any.whl
Collecting pocket (from -r requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/57/b6/cd79a0e237e733e2f8a196f4e9f4d30d99c769b809c5fbbea9e34400655d/pocket-0.3.6.tar.gz
Collecting praw (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/95/71/f3a208d68bf93709c52b4fc110a3c8aab2f68215dcd171ee42c7c3671645/praw-5.4.0-py2.py3-none-any.whl (94kB)
    100% |????????????????????????????????| 102kB 7.4MB/s 
Collecting pushbullet.py (from -r requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/72/91/78912bfb333f412be8f52bba4aa1c9b68d7f612e0fbc9fc5b88b4c894d26/pushbullet.py-0.11.0-py2.py3-none-any.whl
Collecting py-trello (from -r requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/e7/7b/bf3bcf609fc597ca217d330ab7c1f499c8115688fdecdc2a295445253f91/py-trello-0.10.0.tar.gz
Collecting pypandoc (from -r requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz
Collecting python-taiga (from -r requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/e7/db/42896fadd5e69f7071544a355f102dc28c539c4a4b824f89df400352d34e/python_taiga-0.9.0-py2.py3-none-any.whl
Collecting pytidylib (from -r requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/2d/5e/4d2b5e2d443d56f444e2a3618eb6d044c97d14bf47cab0028872c0a468e0/pytidylib-0.3.2.tar.gz (87kB)
    100% |????????????????????????????????| 92kB 7.0MB/s 
Collecting PyTumblr (from -r requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/1c/59/88361fb1ba926a15b594dbf0f2a45816e6cdf9a10a4a1935b369cb19d1bb/PyTumblr-0.0.7-py2.py3-none-any.whl
Collecting pytz (from -r requirements.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl
Collecting requests-oauthlib (from -r requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/77/34/d0957563f20b259a31c12f14e858d79f2e66eb539d3c1b9ab7077ef030ca/requests_oauthlib-0.8.0-py2.py3-none-any.whl
Collecting todoist-python (from -r requirements.txt (line 25))
  Downloading https://files.pythonhosted.org/packages/57/9d/c6b33affe95c66590808a40d61d99a5ff94473dc6ed84127b83119fa4ec3/todoist_python-7.0.18-py2.py3-none-any.whl
Collecting twython (from -r requirements.txt (line 26))
  Downloading https://files.pythonhosted.org/packages/88/33/31f588e972c9b39f937747b1e431239f50b59b18c97c9d24163d8a85df32/twython-3.6.0.tar.gz
Collecting wallabag_api==1.1.3 (from -r requirements.txt (line 27))
  Downloading https://files.pythonhosted.org/packages/b9/02/276a341ca84966f30cb55fc2f1ddd0b16a235c9d8aeae58720f040d3871c/wallabag_api-1.1.3.tar.gz
Collecting python-dateutil (from arrow->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
    100% |????????????????????????????????| 215kB 4.1MB/s 
Collecting regex (from awesome-slugify->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a2/51/c39562cfed3272592c60cfd229e5464d715b78537e332eac2b695422dc49/regex-2018.02.21.tar.gz (620kB)
    100% |????????????????????????????????| 624kB 2.0MB/s 
Collecting Unidecode<0.05,>=0.04.14 (from awesome-slugify->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/01/a1/9d7f3138ee3d79a1ab865a2cb38200ca778d85121db19fe264c76c981184/Unidecode-0.04.21-py2.py3-none-any.whl (228kB)
    100% |????????????????????????????????| 235kB 4.1MB/s 
Collecting six (from django-environ->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting redis>=2.10.0 (from django-redis->-r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/3b/f6/7a76333cf0b9251ecf49efff635015171843d9b977e4ffcf59f9c4428052/redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |????????????????????????????????| 71kB 6.1MB/s 
Collecting oauthlib (from evernote3==1.25.12->-r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/e0/ac/c6a0c98788aa0d61915190d089e9ebe680905a94261effe3936eb8fe356f/oauthlib-2.0.7-py2.py3-none-any.whl (124kB)
    100% |????????????????????????????????| 133kB 6.3MB/s 
Collecting oauth2 (from evernote3==1.25.12->-r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/a0/6f/86db603912ecd04109af952c38bc08928886cf0e34c723481fa7db98b4b5/oauth2-1.9.0.post1-py2.py3-none-any.whl
Collecting requests>=2.0 (from github3.py->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |????????????????????????????????| 92kB 7.0MB/s 
Collecting uritemplate>=3.0.0 (from github3.py->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting decorator (from Mastodon.py->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting update-checker>=0.16 (from praw->-r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/17/c9/ab11855af164d03be0ff4fddd4c46a5bd44799a9ecc1770e01a669c21168/update_checker-0.16-py2.py3-none-any.whl
Collecting prawcore<0.15,>=0.14.0 (from praw->-r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/d7/ee/b30eee52ec96c7fd5e7b9d49627385223ebd861610ef3d7be0f610b01f09/prawcore-0.14.0-py2.py3-none-any.whl
Collecting python-magic (from pushbullet.py->-r requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting websocket-client (from pushbullet.py->-r requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/9d/fb/f51a03e232e00d6c504dfe815aed090c894ba3f8d3f7fd9612f3e227bf24/websocket_client-0.47.0-py2.py3-none-any.whl (200kB)
    100% |????????????????????????????????| 204kB 4.3MB/s 
Requirement already satisfied: setuptools in /home/foxmask/DjangoVirtualEnv/test/lib/python3.6/site-packages (from pypandoc->-r requirements.txt (line 18))
Requirement already satisfied: pip>=8.1.0 in /home/foxmask/DjangoVirtualEnv/test/lib/python3.6/site-packages (from pypandoc->-r requirements.txt (line 18))
Collecting wheel>=0.25.0 (from pypandoc->-r requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl (41kB)
    100% |????????????????????????????????| 51kB 8.6MB/s 
Collecting pyjwkest>=1.0 (from python-taiga->-r requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/f7/a7/e0f2c9754a7638b6bb9573a162b4fd560c89b7b2b3ff278ad072b0714c4b/pyjwkest-1.4.0.tar.gz (41kB)
    100% |????????????????????????????????| 51kB 7.8MB/s 
Collecting future (from PyTumblr->-r requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |????????????????????????????????| 829kB 1.6MB/s 
Collecting httplib2 (from oauth2->evernote3==1.25.12->-r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/fd/ce/aa4a385e3e9fd351737fd2b07edaa56e7a730448465aceda6b35086a0d9b/httplib2-0.11.3.tar.gz (215kB)
    100% |????????????????????????????????| 225kB 4.7MB/s 
Collecting idna<2.7,>=2.5 (from requests>=2.0->github3.py->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |????????????????????????????????| 61kB 7.1MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0->github3.py->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |????????????????????????????????| 143kB 6.5MB/s 
Collecting certifi>=2017.4.17 (from requests>=2.0->github3.py->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |????????????????????????????????| 153kB 6.3MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0->github3.py->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |????????????????????????????????| 133kB 8.0MB/s 
Collecting pycryptodomex (from pyjwkest>=1.0->python-taiga->-r requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/b1/1a/c3f07c05556de1bf0469b92d797708272a7e06ea92be5882e32e9089cee7/pycryptodomex-3.6.1-cp36-cp36m-manylinux1_x86_64.whl (7.3MB)
    100% |????????????????????????????????| 7.3MB 194kB/s 
Installing collected packages: six, python-dateutil, arrow, regex, Unidecode, awesome-slugify, djangorestframework, pytz, Django, django-environ, django-filter, django-formtools, django-js-reverse, redis, django-redis, oauthlib, idna, chardet, certifi, urllib3, requests, requests-oauthlib, httplib2, oauth2, evernote3, feedparser, uritemplate, github3.py, decorator, Mastodon.py, pocket, update-checker, prawcore, praw, python-magic, websocket-client, pushbullet.py, py-trello, wheel, pypandoc, pycryptodomex, future, pyjwkest, python-taiga, pytidylib, PyTumblr, todoist-python, twython, wallabag-api
  Running setup.py install for arrow ... done
  Running setup.py install for regex ... done
  Running setup.py install for awesome-slugify ... done
  Running setup.py install for httplib2 ... done
  Running setup.py install for evernote3 ... done
  Running setup.py install for feedparser ... done
  Running setup.py install for pocket ... done
  Running setup.py install for py-trello ... done
  Running setup.py install for pypandoc ... done
  Running setup.py install for future ... done
  Running setup.py install for pyjwkest ... done
  Running setup.py install for pytidylib ... done
  Running setup.py install for twython ... done
  Running setup.py install for wallabag-api ... done
Successfully installed Django-2.0.4 Mastodon.py-1.2.2 PyTumblr-0.0.7 Unidecode-0.4.21 arrow-0.12.1 awesome-slugify-1.6.5 certifi-2018.4.16 chardet-3.0.4 decorator-4.3.0 django-environ-0.4.4 django-filter-1.1.0 django-formtools-2.1 django-js-reverse-0.8.1 django-redis-4.9.0 djangorestframework-3.8.2 evernote3-1.25.12 feedparser-5.2.1 future-0.16.0 github3.py-1.1.0 httplib2-0.11.3 idna-2.6 oauth2-1.9.0.post1 oauthlib-2.0.7 pocket-0.3.6 praw-5.4.0 prawcore-0.14.0 pushbullet.py-0.11.0 py-trello-0.10.0 pycryptodomex-3.6.1 pyjwkest-1.4.0 pypandoc-1.4 python-dateutil-2.7.2 python-magic-0.4.15 python-taiga-0.9.0 pytidylib-0.3.2 pytz-2018.4 redis-2.10.6 regex-2018.2.21 requests-2.18.4 requests-oauthlib-0.8.0 six-1.11.0 todoist-python-7.0.18 twython-3.6.0 update-checker-0.16 uritemplate-3.0.0 urllib3-1.22 wallabag-api-1.1.3 websocket-client-0.47.0 wheel-0.31.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) ? ~/DjangoVirtualEnv/test/django-th [master|?] 
13:13 $ python manage.py migrate
/home/foxmask/DjangoVirtualEnv/test/lib/python3.6/site-packages/environ/environ.py:624: UserWarning: Error reading /home/foxmask/DjangoVirtualEnv/test/django-th/django_th/.env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_th, sessions, th_evernote, th_github, th_mastodon, th_pelican, th_pocket, th_pushbullet, th_reddit, th_slack, th_taiga, th_todoist, th_trello, th_tumblr, th_twitter, th_wallabag
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying django_th.0001_initial... OK
  Applying django_th.0002_rss_add_uuid... OK
  Applying django_th.0003_rss_populate_uuid_values... OK
  Applying django_th.0004_rss_uuid_remove_uuid_null... OK
  Applying django_th.0005_userservice_altered... OK
  Applying django_th.0006_longer_token... OK
  Applying django_th.0007_trigger_result... OK
  Applying django_th.0008_update_date_result... OK
  Applying django_th.0009_auto_20161113_1553... OK
  Applying django_th.0010_userservice_token... OK
  Applying django_th.0011_digest... OK
  Applying django_th.0012_auto_20171003_2152... OK
  Applying django_th.0013_auto_20171127_2122... OK
  Applying sessions.0001_initial... OK
  Applying th_evernote.0001_initial... OK
  Applying th_github.0001_initial... OK
  Applying th_mastodon.0001_initial... OK
  Applying th_pelican.0001_initial... OK
  Applying th_pocket.0001_initial... OK
  Applying th_pushbullet.0001_initial... OK
  Applying th_reddit.0001_initial... OK
  Applying th_slack.0001_initial... OK
  Applying th_taiga.0001_initial... OK
  Applying th_todoist.0001_initial... OK
  Applying th_trello.0001_initial... OK
  Applying th_tumblr.0001_initial... OK
  Applying th_twitter.0001_initial... OK
  Applying th_twitter.0002_int_to_bigint... OK
  Applying th_twitter.0003_fav... OK
  Applying th_wallabag.0001_initial... OK
(test) ? ~/DjangoVirtualEnv/test/django-th [master|?] 
13:13 $ 
```
I suspect something wrong with AWS (I never used) and SQLite

**Comment by foxmask** [comment]
that works great on VPS, the project is on one of them.
